let mix = require('laravel-mix');
let fs = require('fs');
let path = require('path');

const publicDisplayScripts = [
    'iqamah-shalat-modal.js',
    'kiosk-mode.js',
    'modal-state.js',
    'next-shalat-counter.js',
    'time-calculator.js',
];

function writeGeneratedPublicDisplayScript(fileName) {
    const source = `resources/assets/js/public_display/${fileName}`;
    const output = `public/js/public_display/${fileName}`;
    const generatedFileHeader = [
        `// Generated from ${source}.`,
        '// Do not edit this file directly. Run `yarn dev` after editing the source file.',
        '',
    ].join('\n');

    fs.mkdirSync(path.dirname(output), { recursive: true });
    fs.writeFileSync(output, generatedFileHeader + fs.readFileSync(source, 'utf8'));
}

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.js('resources/assets/js/app.js', 'public/js')
    .then(() => {
        publicDisplayScripts.forEach(writeGeneratedPublicDisplayScript);
    })
    .options({
        processCssUrls: false
    })
   .sass('resources/assets/sass/app.scss', 'public/css');
