let mix = require('laravel-mix');
let fs = require('fs');
let path = require('path');

const publicDisplayModalStateSource = 'resources/assets/js/public_display/modal-state.js';
const publicDisplayModalStateOutput = 'public/js/public_display/modal-state.js';
const generatedFileHeader = [
    '// Generated from resources/assets/js/public_display/modal-state.js.',
    '// Do not edit this file directly. Run `yarn dev` after editing the source file.',
    '',
].join('\n');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.js('resources/assets/js/app.js', 'public/js')
    .then(() => {
        fs.mkdirSync(path.dirname(publicDisplayModalStateOutput), { recursive: true });
        fs.writeFileSync(
            publicDisplayModalStateOutput,
            generatedFileHeader + fs.readFileSync(publicDisplayModalStateSource, 'utf8')
        );
    })
    .options({
        processCssUrls: false
    })
   .sass('resources/assets/sass/app.scss', 'public/css');
